apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: processor-api

resources:
- ../../base

# Adds common labels to all resources
labels:
- includeSelectors: true
  pairs:
    app: processor-api
images:
- name: placeholder-image
  newName: processor-api
  newTag: latest
patches:
##### DEPLOYMENT #####
- target:
    kind: Deployment
    name: deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: processor-api
- path: deployment.yaml
##### SERVICE #####
- target:
    kind: Service
    name: service
  patch: |-
    - op: replace
      path: /metadata/name
      value: processor-api
- path: service.yaml
